#!/bin/sh
# Redirect output to stderr.
exec 1>&2
# enable user input
exec < /dev/tty

# CHECK
if read -p "Do you want to run the linter? (y/n)" yn
then
  echo $yn | grep ^[Yy]$
  if [ $? -eq 0 ]
  then
    CHANGED_FILES=`git diff --staged --name-only | grep \.js* | tr -s '\n' ' '`

    echo $CHANGED_FILES | xargs ./node_modules/.bin/eslint --plugin babel --ext .js,.jsx
  else
    exit 0; #THE USER WANTS TO CONTINUE
  fi
fi
