export default [
  { url: '/blog',               title: 'blog' },
  { url: '/about',              title: 'about' },
  { url: '/about/team',         title: 'team' },
  { url: '/code',               title: 'source code' },
  { url: '/advertising',        title: 'advertise' },
  { url: '/jobs',               title: 'jobs' },
  { url: '/wiki',               title: 'wiki' },
  { url: '/wiki/faq',           title: 'FAQ' },
  { url: '/wiki/reddiquette',   title: 'reddiquette' },
  { url: '/rules',              title: 'rules' },
  { url: '/help/useragreement', title: 'user agreement' },
  { url: '/help/privacypolicy', title: 'privacy policy' },
  { url: '/contact',            title: 'contact us' },
];